Update _progress_bar.py
Fix exception when value is updated before _refresh_timer is instantiated

╭─────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────────────────╮
│ /data/tom/git/abacura/venv/lib/python3.11/site-packages/textual/widgets/_progress_bar.py:347 in updater                                                                                                          │
│                                                                                                                                                                                                                  │
│   344 │   │   │                                                                                ╭───────────── locals ─────────────╮                                                                              │
│   345 │   │   │   def updater(percentage: float | None) -> None:                               │ percentage = 1                   │                                                                              │
│   346 │   │   │   │   """Update the percentage reactive of the enclosed widget."""             │     widget = ETAStatus(id='eta') │                                                                              │
│ ❱ 347 │   │   │   │   widget._percentage = percentage                                          ╰──────────────────────────────────╯                                                                              │
│   348 │   │   │                                                                                                                                                                                                  │
│   349 │   │   │   return updater                                                                                                                                                                                 │
│   350                                                                                                                                                                                                            │
│                                                                                                                                                                                                                  │
│ /data/tom/git/abacura/venv/lib/python3.11/site-packages/textual/widgets/_progress_bar.py:214 in watch__percentage                                                                                                │
│                                                                                                                                                                                                                  │
│   211 │   │   if percentage is None:                                                           ╭───────────── locals ─────────────╮                                                                              │
│   212 │   │   │   self._label_text = "--:--:--"                                                │ percentage = 1                   │                                                                              │
│   213 │   │   else:                                                                            │       self = ETAStatus(id='eta') │                                                                              │
│ ❱ 214 │   │   │   self._refresh_timer.reset()                                                  ╰──────────────────────────────────╯                                                                              │
│   215 │   │   │   self.update_eta()                                                                                                                                                                              │
│   216 │                                                                                                                                                                                                          │
│   217 │   def update_eta(self) -> None:                                                                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'ETAStatus' object has no attribute '_refresh_timer'